package main

import (
	"bytes"
	"encoding/json"
	"fmt"
	"go/format"
	"log"
	"os"
	"path/filepath"
	"regexp"
)

func main() {
	if len(os.Args) != 3 {
		log.Fatalf("Usage: go run generate.go <input_schema.json> <output_schemareader.go>")
	}

	inputFile := os.Args[1]
	outputFile := os.Args[2]

	schemaBytes, err := os.ReadFile(inputFile)
	if err != nil {
		log.Fatalf("Failed to read schema file: %v", err)
	}

	// Validate all patterns inside the schema at generation time to catch Go RE2 incompatibilities
	var parsedSchema interface{}
	if err := json.Unmarshal(schemaBytes, &parsedSchema); err != nil {
		log.Fatalf("Failed to parse schema for pattern validation: %v", err)
	}

	supportedFormats := map[string]bool{
		"ipv4": true, "ipv6": true, "uc-ip": true, "uc-mac": true,
		"uc-timeout": true, "uc-portrange": true, "uc-cidr4": true, "uc-cidr6": true,
		"hostname": true, "uc-cidr": true, "uc-mobility": true, "uc-base64": true,
		"uc-fqdn": true, "uc-host": true, "uri": true,
	}

	allowedKeywords := map[string]bool{
		"type": true, "properties": true, "patternProperties": true, "items": true,
		"required": true, "enum": true, "minimum": true, "maximum": true,
		"minLength": true, "maxLength": true, "minItems": true, "maxItems": true,
		"format": true, "pattern": true, "oneOf": true, "anyOf": true,
		"allOf": true, "additionalProperties": true, "const": true,
		"exclusiveMinimum": true, "exclusiveMaximum": true, "multipleOf": true,
		"minProperties": true, "maxProperties": true, "propertyNames": true,
		// Metadata and JSON Schema boilerplate
		"title": true, "description": true, "decription": true, "default": true, "examples": true, "example": true,
		"readOnly": true, "writeOnly": true, "$schema": true, "$id": true,
		"$$target": true, "definitions": true, "$defs": true,
	}

	var validateSchema func(node interface{}, path string, isSchema bool)
	validateSchema = func(node interface{}, path string, isSchema bool) {
		switch n := node.(type) {
		case map[string]interface{}:
			for k, v := range n {
				if isSchema {
					if !allowedKeywords[k] {
						log.Fatalf("Error: JSON Schema contains unsupported keyword %q at %s. Please implement it or add to allowlist.", k, path)
					}
					if k == "$ref" {
						log.Fatalf("Error: JSON Schema contains unresolved reference %q at %s. Go generator requires fully dereferenced schemas.", v, path)
					}
					if k == "format" {
						if formatStr, ok := v.(string); ok {
							if !supportedFormats[formatStr] {
								log.Fatalf("Error: JSON Schema contains unsupported format %q at %s. Please implement it in generate-reader.go.", formatStr, path)
							}
						}
					}
					if k == "pattern" {
						if patStr, ok := v.(string); ok {
							if _, err := regexp.Compile(patStr); err != nil {
								log.Fatalf("Error: JSON Schema pattern %q at %s is not valid Go RE2 syntax: %v", patStr, path, err)
							}
						}
					}
					if k == "patternProperties" {
						if patProps, ok := v.(map[string]interface{}); ok {
							for pat := range patProps {
								if _, err := regexp.Compile(pat); err != nil {
									log.Fatalf("Error: JSON Schema patternProperty %q at %s is not valid Go RE2 syntax: %v", pat, path, err)
								}
							}
						}
					}
				}
				nextIsSchema := true
				if k == "properties" || k == "patternProperties" || k == "definitions" || k == "$defs" || k == "default" || k == "examples" || k == "enum" || k == "const" {
					nextIsSchema = false
				}
				validateSchema(v, path+"."+k, nextIsSchema)
			}
		case []interface{}:
			for i, v := range n {
				validateSchema(v, fmt.Sprintf("%s[%d]", path, i), isSchema)
			}
		}
	}
	validateSchema(parsedSchema, "$", true)

	// Escape backticks in the JSON payload so we can embed it inside a raw string literal
	schemaString := bytes.ReplaceAll(schemaBytes, []byte("`"), []byte("`+\"`\"+`"))

	outDir := filepath.Dir(outputFile)
	if err := os.MkdirAll(outDir, 0755); err != nil {
		log.Fatalf("Failed to create output directory: %v", err)
	}

	goCode := fmt.Sprintf(`// Code generated by generators/go/generate-reader.go. DO NOT EDIT.
package validator

import (
	"bytes"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"io"
	"math"
	"net/netip"
	"reflect"
	"regexp"
	"strconv"
	"strings"
)

// SchemaJSON contains the fully resolved uCentral JSON schema
const SchemaJSON = `+"`%s`"+`

type Schema struct {
	Type                 interface{}             `+"`json:\"type\"`"+`
	Properties           map[string]*Schema      `+"`json:\"properties\"`"+`
	PatternProperties    map[string]*Schema      `+"`json:\"patternProperties\"`"+`
	Items                *Schema                 `+"`json:\"items\"`"+`
	Required             []string                `+"`json:\"required\"`"+`
	Enum                 []interface{}           `+"`json:\"enum\"`"+`
	Minimum              *float64                `+"`json:\"minimum\"`"+`
	Maximum              *float64                `+"`json:\"maximum\"`"+`
	MinLength            *int                    `+"`json:\"minLength\"`"+`
	MaxLength            *int                    `+"`json:\"maxLength\"`"+`
	MinItems             *int                    `+"`json:\"minItems\"`"+`
	MaxItems             *int                    `+"`json:\"maxItems\"`"+`
	Format               string                  `+"`json:\"format\"`"+`
	Pattern              string                  `+"`json:\"pattern\"`"+`
	OneOf                []*Schema               `+"`json:\"oneOf\"`"+`
	AnyOf                []*Schema               `+"`json:\"anyOf\"`"+`
	AllOf                []*Schema               `+"`json:\"allOf\"`"+`
	AdditionalProperties *bool                   `+"`json:\"additionalProperties\"`"+`
	Const                interface{}             `+"`json:\"const\"`"+`
	ExclusiveMinimum     *float64                `+"`json:\"exclusiveMinimum\"`"+`
	ExclusiveMaximum     *float64                `+"`json:\"exclusiveMaximum\"`"+`
	MultipleOf           *float64                `+"`json:\"multipleOf\"`"+`
	MinProperties        *int                    `+"`json:\"minProperties\"`"+`
	MaxProperties        *int                    `+"`json:\"maxProperties\"`"+`
	PropertyNames        *Schema                 `+"`json:\"propertyNames\"`"+`
	HasConst             bool                    `+"`json:\"-\"`"+`
}

type rawSchema Schema

func (s *Schema) UnmarshalJSON(data []byte) error {
	var rs rawSchema
	if err := json.Unmarshal(data, &rs); err != nil {
		return err
	}
	*s = Schema(rs)

	var raw map[string]interface{}
	if err := json.Unmarshal(data, &raw); err == nil {
		if _, exists := raw["const"]; exists {
			s.HasConst = true
		}
	}
	return nil
}

var rootSchema *Schema
var compiledPatterns map[string]*regexp.Regexp

var (
	ucMacRegex       = regexp.MustCompile(`+"`^([0-9A-Fa-f]{2}:){5}([0-9A-Fa-f]{2})$`"+`)
	ucTimeoutRegex   = regexp.MustCompile(`+"`^[0-9]+[smhdw]$`"+`)
	ucPortRangeRegex = regexp.MustCompile(`+"`^([0-9]|[1-9][0-9]*)(-([0-9]|[1-9][0-9]*))?$`"+`)
	strictLabelRegex = regexp.MustCompile(`+"`^([a-zA-Z0-9]{1,2}|[a-zA-Z0-9][a-zA-Z0-9-]{0,61}[a-zA-Z0-9])$`"+`)
	looseLabelRegex  = regexp.MustCompile(`+"`^([a-zA-Z0-9]|[a-zA-Z0-9][a-zA-Z0-9-]{0,61}[a-zA-Z0-9])$`"+`)
	ucMobilityRegex  = regexp.MustCompile("^([0-9A-Fa-f]{4})$")
	uriRegex         = regexp.MustCompile(`+"`^[a-z+-]+://([^/]+).*$`"+`)
	ipv4Regex        = regexp.MustCompile(`+"`^([0-9]{1,3}\\.){3}[0-9]{1,3}$`"+`)
)

func isValidHostname(value string, minLabels int, strict bool) bool {
	if len(value) > 255 {
		return false
	}
	labels := strings.Split(value, ".")
	if len(labels) < minLabels {
		return false
	}
	r := looseLabelRegex
	if strict {
		r = strictLabelRegex
	}
	for _, label := range labels {
		if !r.MatchString(label) {
			return false
		}
	}
	return true
}

func isValidIPv4(val string) bool {
	if !ipv4Regex.MatchString(val) {
		return false
	}
	parts := strings.Split(val, ".")
	if len(parts) != 4 {
		return false
	}
	for _, part := range parts {
		num, err := strconv.Atoi(part)
		if err != nil || num < 0 || num > 255 {
			return false
		}
	}
	return true
}

func init() {
	d := json.NewDecoder(strings.NewReader(SchemaJSON))
	d.UseNumber()
	if err := d.Decode(&rootSchema); err != nil {
		panic(fmt.Sprintf("failed to load embedded schema: %%v", err))
	}
	compiledPatterns = make(map[string]*regexp.Regexp)
	precompilePatterns(rootSchema)
}

func precompilePatterns(s *Schema) {
	if s == nil { return }
	if s.Pattern != "" {
		compiledPatterns[s.Pattern] = regexp.MustCompile(s.Pattern)
	}
	for k, v := range s.PatternProperties {
		compiledPatterns[k] = regexp.MustCompile(k)
		precompilePatterns(v)
	}
	for _, v := range s.Properties {
		precompilePatterns(v)
	}
	for _, v := range s.OneOf {
		precompilePatterns(v)
	}
	for _, v := range s.AnyOf {
		precompilePatterns(v)
	}
	for _, v := range s.AllOf {
		precompilePatterns(v)
	}
	precompilePatterns(s.Items)
	precompilePatterns(s.PropertyNames)
}

func Validate(configJSON []byte) error {
	var v interface{}
	d := json.NewDecoder(bytes.NewReader(configJSON))
	d.UseNumber()
	if err := d.Decode(&v); err != nil {
		return fmt.Errorf("invalid json payload: %%w", err)
	}
	var extra interface{}
	if err := d.Decode(&extra); err != io.EOF {
		return fmt.Errorf("invalid json payload: trailing data")
	}
	if errs := validateNode(rootSchema, v, "$"); len(errs) > 0 {
		return fmt.Errorf("validation failed: %%s", strings.Join(errs, "; "))
	}
	return nil
}

func validateNode(s *Schema, v interface{}, path string) []string {
	if s == nil { return nil }
	var errs []string

	// 1. Type validation
	if s.Type != nil {
		validType := false
		switch t := s.Type.(type) {
		case string:
			validType = checkType(t, v)
		case []interface{}:
			for _, allowedType := range t {
				if checkType(fmt.Sprint(allowedType), v) {
					validType = true
					break
				}
			}
		}
		if !validType {
			if v == nil {
				return []string{fmt.Sprintf("%%s: must not be null", path)}
			}
			return []string{fmt.Sprintf("%%s: invalid type", path)}
		}
	}

	// 2. Object validation
	if obj, ok := v.(map[string]interface{}); ok {
		if s.MinProperties != nil && len(obj) < *s.MinProperties {
			errs = append(errs, fmt.Sprintf("%%s: must have at least %%d properties", path, *s.MinProperties))
		}
		if s.MaxProperties != nil && len(obj) > *s.MaxProperties {
			errs = append(errs, fmt.Sprintf("%%s: must have at most %%d properties", path, *s.MaxProperties))
		}
		for _, req := range s.Required {
			if _, exists := obj[req]; !exists {
				errs = append(errs, fmt.Sprintf("%%s: missing required property '%%s'", path, req))
			}
		}
		for key, val := range obj {
			if s.PropertyNames != nil {
				errs = append(errs, validateNode(s.PropertyNames, key, fmt.Sprintf("%%s.%%s(propertyName)", path, key))...)
			}
			matched := false
			if propSchema, exists := s.Properties[key]; exists {
				errs = append(errs, validateNode(propSchema, val, path+"."+key)...)
				matched = true
			}
			for pat, propSchema := range s.PatternProperties {
				if r := compiledPatterns[pat]; r != nil && r.MatchString(key) {
					errs = append(errs, validateNode(propSchema, val, path+"."+key)...)
					matched = true
				}
			}
			if !matched && s.AdditionalProperties != nil && !*s.AdditionalProperties {
				errs = append(errs, fmt.Sprintf("%%s.%%s: additional property is not allowed", path, key))
			}
		}
	}

	// 3. Array validation
	if arr, ok := v.([]interface{}); ok {
		if s.MinItems != nil && len(arr) < *s.MinItems {
			errs = append(errs, fmt.Sprintf("%%s: must have at least %%d items", path, *s.MinItems))
		}
		if s.MaxItems != nil && len(arr) > *s.MaxItems {
			errs = append(errs, fmt.Sprintf("%%s: must have at most %%d items", path, *s.MaxItems))
		}
		if s.Items != nil {
			for i, item := range arr {
				errs = append(errs, validateNode(s.Items, item, fmt.Sprintf("%%s[%%d]", path, i))...)
			}
		}
	}

	// 4. String validation
	if str, ok := v.(string); ok {
		strLen := utf16Length(str)
		if s.MinLength != nil && strLen < *s.MinLength {
			errs = append(errs, fmt.Sprintf("%%s: length must be >= %%d", path, *s.MinLength))
		}
		if s.MaxLength != nil && strLen > *s.MaxLength {
			errs = append(errs, fmt.Sprintf("%%s: length must be <= %%d", path, *s.MaxLength))
		}
		if s.Pattern != "" {
			if r := compiledPatterns[s.Pattern]; r != nil && !r.MatchString(str) {
				errs = append(errs, fmt.Sprintf("%%s: does not match pattern %%s", path, s.Pattern))
			}
		}
		if s.Format != "" {
			if !checkFormat(s.Format, str) {
				errs = append(errs, fmt.Sprintf("%%s: invalid format '%%s'", path, s.Format))
			}
		}
	}

	// 5. Number validation
	if num, ok := getFloat64(v); ok {
		if s.Minimum != nil && num < *s.Minimum {
			errs = append(errs, fmt.Sprintf("%%s: must be >= %%v", path, *s.Minimum))
		}
		if s.Maximum != nil && num > *s.Maximum {
			errs = append(errs, fmt.Sprintf("%%s: must be <= %%v", path, *s.Maximum))
		}
		if s.ExclusiveMinimum != nil && num <= *s.ExclusiveMinimum {
			errs = append(errs, fmt.Sprintf("%%s: must be > %%v", path, *s.ExclusiveMinimum))
		}
		if s.ExclusiveMaximum != nil && num >= *s.ExclusiveMaximum {
			errs = append(errs, fmt.Sprintf("%%s: must be < %%v", path, *s.ExclusiveMaximum))
		}
		if s.MultipleOf != nil {
			div := num / *s.MultipleOf
			if math.Abs(div-math.Round(div)) > 1e-9 {
				errs = append(errs, fmt.Sprintf("%%s: must be a multiple of %%v", path, *s.MultipleOf))
			}
		}
	}

	// 6. Enum validation
	if len(s.Enum) > 0 {
		matched := false
		for _, e := range s.Enum {
			if isEqual(e, v) {
				matched = true
				break
			}
		}
		if !matched {
			errs = append(errs, fmt.Sprintf("%%s: value not in enum", path))
		}
	}

	if s.HasConst {
		if !isEqual(s.Const, v) {
			errs = append(errs, fmt.Sprintf("%%s: value must match const", path))
		}
	}

	if len(s.OneOf) > 0 {
		matchCount := 0
		for i, subSchema := range s.OneOf {
			if len(validateNode(subSchema, v, fmt.Sprintf("%%s.oneOf[%%d]", path, i))) == 0 {
				matchCount++
			}
		}
		if matchCount != 1 {
			errs = append(errs, fmt.Sprintf("%%s: must match exactly one schema in oneOf", path))
		}
	}

	if len(s.AnyOf) > 0 {
		matched := false
		for i, subSchema := range s.AnyOf {
			if len(validateNode(subSchema, v, fmt.Sprintf("%%s.anyOf[%%d]", path, i))) == 0 {
				matched = true
				break
			}
		}
		if !matched {
			errs = append(errs, fmt.Sprintf("%%s: must match at least one schema in anyOf", path))
		}
	}

	if len(s.AllOf) > 0 {
		for _, subSchema := range s.AllOf {
			subErrs := validateNode(subSchema, v, path)
			if len(subErrs) > 0 {
				errs = append(errs, subErrs...)
			}
		}
	}

	return errs
}

func checkType(expected string, v interface{}) bool {
	switch expected {
	case "string":
		_, ok := v.(string)
		return ok
	case "number":
		if jn, ok := v.(json.Number); ok {
			_, err := jn.Float64()
			return err == nil
		}
		_, ok := v.(float64)
		return ok
	case "integer":
		if jn, ok := v.(json.Number); ok {
			_, err := jn.Int64()
			if err == nil {
				return true
			}
			f, err := jn.Float64()
			return err == nil && !math.IsNaN(f) && !math.IsInf(f, 0) && f == math.Trunc(f)
		}
		f, ok := v.(float64)
		return ok && !math.IsNaN(f) && !math.IsInf(f, 0) && f == math.Trunc(f)
	case "boolean":
		_, ok := v.(bool)
		return ok
	case "object":
		_, ok := v.(map[string]interface{})
		return ok
	case "array":
		_, ok := v.([]interface{})
		return ok
	case "null":
		return v == nil
	default:
		return false
	}
}

func checkFormat(format string, val string) bool {
	switch format {
	case "ipv4":
		return isValidIPv4(val)
	case "ipv6":
		ip, err := netip.ParseAddr(val)
		return err == nil && ip.Is6()
	case "uc-ip":
		if isValidIPv4(val) {
			return true
		}
		ip, err := netip.ParseAddr(val)
		return err == nil && ip.Is6()
	case "uc-mac":
		return ucMacRegex.MatchString(val)
	case "uc-timeout":
		return ucTimeoutRegex.MatchString(val)
	case "uc-portrange":
		matches := ucPortRangeRegex.FindStringSubmatch(val)
		if matches == nil {
			return false
		}
		min, err := strconv.Atoi(matches[1])
		if err != nil || min > 65535 {
			return false
		}
		max := min
		if matches[3] != "" {
			max, err = strconv.Atoi(matches[3])
			if err != nil || max > 65535 {
				return false
			}
		}
		return max >= min
	case "uc-cidr4":
		parts := strings.Split(val, "/")
		if len(parts) != 2 {
			return false
		}
		prefix, err := strconv.Atoi(parts[1])
		if err != nil || prefix < 0 || prefix > 32 {
			return false
		}
		if parts[0] == "auto" {
			return true
		}
		return isValidIPv4(parts[0])
	case "uc-cidr6":
		parts := strings.Split(val, "/")
		if len(parts) != 2 {
			return false
		}
		prefix, err := strconv.Atoi(parts[1])
		if err != nil || prefix < 0 || prefix > 128 {
			return false
		}
		if parts[0] == "auto" {
			return true
		}
		ip, err := netip.ParseAddr(parts[0])
		return err == nil && ip.Is6()
	case "hostname":
		return isValidHostname(val, 1, true)
	case "uc-cidr":
		parts := strings.Split(val, "/")
		if len(parts) != 2 {
			return false
		}
		prefix, err := strconv.Atoi(parts[1])
		if err != nil {
			return false
		}
		if parts[0] == "auto" {
			return prefix >= 0 && prefix <= 128
		}
		if isValidIPv4(parts[0]) {
			return prefix >= 0 && prefix <= 32
		}
		ip, err := netip.ParseAddr(parts[0])
		if err == nil && ip.Is6() {
			return prefix >= 0 && prefix <= 128
		}
		return false
	case "uc-mobility":
		return ucMobilityRegex.MatchString(val)
	case "uc-base64":
		if _, err := base64.StdEncoding.DecodeString(val); err == nil {
			return true
		}
		if _, err := base64.RawStdEncoding.DecodeString(val); err == nil {
			return true
		}
		return false
	case "uc-fqdn":
		return isValidHostname(val, 2, true)
	case "uc-host":
		if isValidIPv4(val) {
			return true
		}
		ip, err := netip.ParseAddr(val)
		if err == nil && ip.Is6() {
			return true
		}
		return isValidHostname(val, 1, false)
	case "uri":
		if strings.HasPrefix(val, "data:") {
			return true
		}
		matches := uriRegex.FindStringSubmatch(val)
		if matches == nil {
			return false
		}
		host := matches[1]
		if isValidIPv4(host) {
			return true
		}
		ip, err := netip.ParseAddr(host)
		if err == nil && ip.Is6() {
			return true
		}
		return isValidHostname(host, 1, false)
	}
	return true
}

func getFloat64(v interface{}) (float64, bool) {
	switch n := v.(type) {
	case float64:
		return n, true
	case json.Number:
		f, err := n.Float64()
		return f, err == nil
	}
	return 0, false
}

func isEqual(a, b interface{}) bool {
	if reflect.DeepEqual(a, b) {
		return true
	}
	if fa, ok := getFloat64(a); ok {
		if fb, ok := getFloat64(b); ok {
			return fa == fb
		}
	}
	if sa, ok := a.([]interface{}); ok {
		if sb, ok := b.([]interface{}); ok {
			if len(sa) != len(sb) {
				return false
			}
			for i := range sa {
				if !isEqual(sa[i], sb[i]) {
					return false
				}
			}
			return true
		}
	}
	if ma, ok := a.(map[string]interface{}); ok {
		if mb, ok := b.(map[string]interface{}); ok {
			if len(ma) != len(mb) {
				return false
			}
			for k, va := range ma {
				vb, ok := mb[k]
				if !ok || !isEqual(va, vb) {
					return false
				}
			}
			return true
		}
	}
	return false
}

func utf16Length(s string) int {
	length := 0
	for _, r := range s {
		if r > 0xffff {
			length += 2
		} else {
			length++
		}
	}
	return length
}
`, schemaString)

	formattedCode, err := format.Source([]byte(goCode))
	if err != nil {
		log.Fatalf("Failed to format generated code: %v", err)
	}

	if err := os.WriteFile(outputFile, formattedCode, 0644); err != nil {
		log.Fatalf("Failed to write output file: %v", err)
	}

	fmt.Printf("Successfully generated %s\n", outputFile)
}
